In [ ]:
import torch

inputs = torch.tensor(
    [[0.43, 0.15, 0.89], #your
     [0.55, 0.87, 0.66], #journey
     [0.57, 0.85, 0.64], #starts
     [0.22, 0.58, 0.33], #with
     [0.77, 0.25, 0.10], #one
     [0.05, 0.80, 0.55]] #step
)

In [9]:
# journey
input_query = inputs[1]
input_query

tensor([0.5500, 0.8700, 0.6600])

In [10]:
input_1 = inputs[0]
input_1

tensor([0.4300, 0.1500, 0.8900])

In [11]:
torch.dot(input_query, input_1)

tensor(0.9544)

In [13]:
query = inputs[1]

attn_scores_2 = torch.empty(inputs.shape[0])

for i, x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(x_i, query)

print(attn_scores_2)


tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])
